[package]
name = "integrity"
version = "0.1.0"
authors = ["Mario Marhuenda <marioytambor@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob=""
