<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="$lang$" xml:lang="$lang$"$if(dir)$ dir="$dir$"$endif$>
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
$for(author-meta)$
  <meta name="author" content="$author-meta$" />
$endfor$
$if(date-meta)$
  <meta name="dcterms.date" content="$date-meta$" />
$endif$
$if(keywords)$
  <meta name="keywords" content="$for(keywords)$$keywords$$sep$, $endfor$" />
$endif$
$if(description-meta)$
  <meta name="description" content="$description-meta$" />
$endif$
  <title>$if(title-prefix)$$title-prefix$ – $endif$$pagetitle$</title>
  <style>
    $styles.html()$
  </style>
$for(css)$
  <link rel="stylesheet" href="$css$" />
$endfor$
$if(math)$
  $math$
$endif$
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
$for(header-includes)$
  $header-includes$
$endfor$
<link rel=icon type=image/png href="$path$pix/head.png">
</head>
<body>
$for(include-before)$
$include-before$
$endfor$
$if(title)$
<header id="title-block-header">
<h1 class="title">$title$</h1>
$if(subtitle)$
<p class="subtitle">$subtitle$</p>
$endif$
$for(author)$
<p class="author">$author$</p>
$endfor$
$if(date)$
<p class="date">$date$</p>
$endif$
</header>
$endif$

<?php
/*Here the idea is that nav should be automatically 
 * generated by php*/
?>

<nav>
     <ul>
<?php
     $db = new SQLite3('db/web.sqlite3');
$results = $db->query('select * from nav');
 
while ($row=$results->fetchArray()){
    $path = $row["path"];
    $logo = $row["logo"];
    $name = $row["name"];
    if (!(strpos($path,'https')!== false)){
        $path="\$path\$public$path";
    }
    ?>
          <a href="<?php echo "$path";?>">
                 <li class='underline-animation'><?php echo "$name";?>

<?php if (!empty($logo)){ echo "<img src=\"\$path\$pix/$logo\""; echo "alt=$logo/>";} ?>
           </li></a>
<?php
}
?>
    </ul>
</nav>



$for(include-after)$
$include-after$
$endfor$
<main>
$body$
</main>
</body>

<footer>
    Inspired by: <a href="https://lukesmith.xyz">Luke Smith's Webpage</a>
    Everything available under
    <a href="LICENSE">
    GPL 3.0 license.</a>
</footer>
</html>
