<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="$lang$" xml:lang="$lang$"$if(dir)$ dir="$dir$"$endif$>
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
$for(author-meta)$
  <meta name="author" content="$author-meta$" />
$endfor$
$if(date-meta)$
  <meta name="dcterms.date" content="$date-meta$" />
$endif$
$if(keywords)$
  <meta name="keywords" content="$for(keywords)$$keywords$$sep$, $endfor$" />
$endif$
$if(description-meta)$
  <meta name="description" content="$description-meta$" />
$endif$
  <title>$if(title-prefix)$$title-prefix$ – $endif$$pagetitle$</title>
  <style>
    $styles.html()$
  </style>
$for(css)$
  <link rel="stylesheet" href="$css$" />
$endfor$
$if(math)$
  $math$
$endif$
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
$for(header-includes)$
  $header-includes$
$endfor$
<link rel=icon type=image/png href="$path$pix/head.png">
</head>
<body>
$for(include-before)$
$include-before$
$endfor$
$if(title)$
<header id="title-block-header">
<h1 class="title">$title$</h1>
$if(subtitle)$
<p class="subtitle">$subtitle$</p>
$endif$
$for(author)$
<p class="author">$author$</p>
$endfor$
$if(date)$
<p class="date">$date$</p>
$endif$
</header>
$endif$

<?php
/*Here the idea is that nav should be automatically 
 * generated by php*/
?>

<nav>
    <ul>
        <a href="$path$index.html">
            <li class="underline-animation"> Home</li>
        </a>
        <a href="$path$public/blog/index.html">
            <li> Blog</li>
        </a>
<?php
     $db = new SQLite3('db/web.sqlite3');
     $results = $db->query('select * from nav');
 
     while ($row=$results->fetchArray()){
         ?>
         <a href=<?php '\$path\$public$row["path"]'?>>
                <li img src=<?php '\$path\$pix$row["logo"]'?>
                alt=<?php 'row["logo"]'?>
                class='underline-animation'> <?php row["name"]?></li>
         </a>
         <?php
     }
?>
/*
            <div class="dropdown-content">
                <a href="$path$public/blog/math/index.html"> Math</a>
                <a href="$path$public/blog/chess/index.html"> Chess</a>
                <a href="$path$public/blog/math/liesofhighschool/index.html"> Lies of high school</a>
           </div>
 */
?>
        <a href="https://github.com/marhu98">
            <li><img src="$path$pix/git.svg" alt="Github logo"> Software</li></a>
        <a href="$path$public/contact/index.html">
            <li> Contact</li></a>
        <a href="$path$pulic/rants/index.html">
            <li> Rants</li></a>
        <a href="$path$rss.xml">
            <li><img src="$path$pix/rss.svg" alt="rss logo"> RSS</li></a>
    </ul>
</nav>



$for(include-after)$
$include-after$
$endfor$
<main>
$body$
</main>
</body>

<footer>
    Inspired by: <a href="https://lukesmith.xyz">Luke Smith's Webpage</a>
    Everything available under
    <a href="LICENSE">
    GPL 3.0 license.</a>
</footer>
</html>
